# -*- coding: utf-8 -*-
"""Credits.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkTejE75aHjURGRvV5GY4OJcg2XRSm_w
"""

print("Names of all courses in this semester:")
print("1. HPC - 4 \n2. DevOps - 2 \n3. SPM - 2 \n4. EVS - 1 \n5. Career Skills - 3 \n6. Communication Skills - 2 \n7. Seminar on Special Topics - 1 \n8. Capstone Design - 2 \n9. Undergraduate Research - 2")